### ISSUE TITLE
Expand graph/scene not successful

### ISSUE THREAD

**Issue by sgdgp** [xavierpuigf/virtualhome#11]
Hi,
I tried executing one of the programs given in the executable script directory of TrimmedTestScene1.
However I am not able to render the video correctly.
The file chosen : 
`executable_programs/TrimmedTestScene1_graph/results_intentions_march-13-18/file499_1.txt`

The init graph is also chosen accordingly from the folder `init_and_final_graph`.
I am using `render_script_from_path()` function from `execute_script_utils.py`.

The error is :  
`{'succes_expand': False, 'message': ('Some objects appearing in the script were not properly initialized', ['handsboth', 'soap', 'papertowel'])}`

I expect that this script should have rendered properly as it was in the executable programs directory. @xavierpuigf  Could you please explain what is going wrong here or what I am missing here ?

**Comment by sgdgp** [comment]
@xavierpuigf I am still facing the same issue. 
Could you please help me out ?

**Comment by wetoo-cando** [comment]
Hi @sgdgp !

Where do you have the `executable_programs` and `init_and_final_graph` directories from?

I downloaded the dataset from: http://virtual-home.org/release/programs/programs_processed_precond_nograb_morepreconds.zip. It doesn't contain those directories. Do you somehow have to generate them?

Best,
Rahul

**Comment by xavierpuigf** [comment]
Hi @sgdgp,

The message you obtained is saying that some of the objects failed to be included in the scene. This is because some of the objects that appear in the dataset of scripts do not exist in the Unity executable. This is fine, as long as these objects do not appear directly in the script (that is, the agent does not interact with these objects directly). Those objects serve as background objects and should not modify the behavior of the script that is being executed.

@wetoo-cando , that is right, you need to use evolve_graph in order to generate those folders.  If you look at `demo/generate_snapshot.py` you can see an example of how the files are created. You can find more info here https://github.com/xavierpuigf/virtualhome/blob/master/dataset/README.md

**Comment by Kalcy-U** [comment]
Hi! I am facing the same problem, may I ask how you solved it?
