### ISSUE TITLE
Why are some scripts invalid

### ISSUE THREAD

**Issue by onlyonewater** [xavierpuigf/virtualhome#27]
Hi, @xavierpuigf , when my script = ['<char0> [walk] <window> ({})'.format(window_id),], the simulator is not working, and the agent is always in the same place, but when my script = ['<char0> [walk] <curtains> ({})'.format(curtain_id)], the Agent walked towards the curtain. I am very confused. Why???Are there any rules for script??? Thanks!!!

**Comment by xavierpuigf** [comment]
Hi! You need to enter the object name, besides the id, in this case the script should be
`[' [walk] <window> ({})'.format(window_id)]`

**Comment by onlyonewater** [comment]
Oh, yes, I enter the object name, but it doesn't seem to show up. `'<char0> [walk] <window> ({})'.format(window_id)`, and `'<char0> [walk] <curtains> ({})'.format(curtain_id)`. I don't know why.

**Comment by xavierpuigf** [comment]
I believe that some of the curtains have an issue because they don't have a collider. We need to work on including them in the future. For now, to make sure that you can interact with an object, you need to check that the object appears as a key in this dictionary: https://github.com/xavierpuigf/virtualhome/blob/master/resources/prefabs_dims.json
